CREATE TABLE Rule (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  maxSecondsPerRequest BIGINT NOT NULL,
  maxRequest BIGINT NOT NULL,
  dateCreated VARCHAR(255) NOT NULL,
  createdBy VARCHAR(255) NOT NULL
);


CREATE TABLE Client (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ipAddress VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  dateCreated VARCHAR(255) NOT NULL,
  createdBy VARCHAR(255) NOT NULL
);


CREATE TABLE ClientRule(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  clientId BIGINT NOT NULL,
  ruleId BIGINT NOT NULL,
  status VARCHAR(255) NOT NULL,
  dateCreated VARCHAR(255) NOT NULL,
  createdBy VARCHAR(255) NOT NULL
);




